### ISSUE TITLE
Can't install the module

### ISSUE THREAD

**Issue by Seboon** [g3w-suite/g3w-admin-elevation-profile#3]
Hi,

I'm trying to add the module after a fresh install of g3w-suite-docker (v3.6.x)  without any success.
Does it need to build g3w-suite with a raw installation?
Also there are two repositories : g3w-admin-elevation-profile and  g3w-client-plugin-elevation-profile. Which one is the good one,or do we have to install both of them??
Thanks in advance if you can give me deeper instructions!

**Comment by Seboon** [comment]
Ok, found the solution , based on [https://stackoverflow.com/questions/55929472/django-templatesyntaxerror-staticfiles-is-not-a-registered-tag-library](url).
You need to change {% load staticfiles %} to {% load static %} in each files inside the folder tempaltes/eleprofile.

**Comment by wlorenzetti** [comment]
Hi @Seboon, yes this is a old plugins not more used and porting to Django 3.2 was not done.
